# ============================
# geometry parameters
# ============================
[geometry]
# this is 1 pixel = how many cm
scale_factor = 20 

# ============================
# Phenotyping
# ============================
[trait1]
d = 25

[trait2]
d = 25

[trait3]
d = 25
e = 1

[trait4]
d = 25

[trait5]
r_in = 20
r_out = 50




