# ============================
# geometry parameters
# ============================
[geometry]
# this is 1 pixel = how many cm
scale_factor = 0.099800399201
fps = 25

# ============================
# Phenotyping
# ============================
[trait1]
r = 25

[trait2]
r = 25

[trait3]
r = 25
e = 1

[trait4]
r = 25

[trait5]
r_in = 20
r_out = 50




